import React, { cache } from 'react';
import './globals.css';
import type { Metadata } from 'next';
import { Josefin_Sans, Bayon } from 'next/font/google';
import NavBar from '@/components/navigation/NavBar';
import ReduxProvider from '@/store/ReduxProvider';
import {
  getAllDesktopNavigationLinks,
  getAllNavigationLinks,
  getAllSocialMedia,
} from '@/lib/queries';
import client from '../../sanity/lib/client';

const josefin = Josefin_Sans({
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-josefin',
});

const bayon = Bayon({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-bayon',
});

export const metadata: Metadata = {
  title: 'Rakonto',
  description: 'Generated by create next app',
};

export const revalidate = 60;

const clientFetch = cache(client.fetch.bind(client));

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const navLinks = await clientFetch(getAllNavigationLinks);
  const desktopNavLinks = await clientFetch(getAllDesktopNavigationLinks);
  const socialMedia = await clientFetch(getAllSocialMedia);

  return (
    <html className="bg-background flex items-center justify-center" lang="en">
      <body
        className={`${josefin.variable} ${bayon.variable}  w-full max-w-content  `}
      >
        <ReduxProvider>
          <NavBar
            navLinks={navLinks}
            desktopNavLinks={desktopNavLinks}
            socialMedia={socialMedia}
          />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
