import React from 'react';
import './globals.css';
import type { Metadata } from 'next';
import { Josefin_Sans, Bayon } from 'next/font/google';
import NavBar from '@/components/navigation/NavBar';
import ReduxProvider from '@/store/ReduxProvider';

const josefin = Josefin_Sans({
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-josefin',
});

const bayon = Bayon({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-bayon',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="bg-background flex items-center justify-center" lang="en">
      <body
        className={`${josefin.variable} ${bayon.variable} max-w-content w-full`}
      >
        <ReduxProvider>
          <NavBar />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
